# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# author : @rizky nugraha herliyanto


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtSql import *
from main import *
from datetime import date
import Source

class Ui_Dialog(QWidget):
        def setupUi(self, Dialog):
                Dialog.setObjectName("Dialog")
                Dialog.resize(939, 650)
                Dialog.setWindowFlags(QtCore.Qt.FramelessWindowHint)
                
                #-----------label untuk get Id akun----------#
                self.labelId = QLabel()
                self.labelId.setText("")
                #--------------------------------------------#
                
                self.lblJmlAnggota = QLabel("")
                
                self.tabWDashboard = QtWidgets.QTabWidget(Dialog)
                self.tabWDashboard.setGeometry(QtCore.QRect(-10, 135, 961, 521))
                self.tabWDashboard.setStyleSheet("QTabWidget::pane {\n"
        "    /*background-color: rgb(137, 204, 247);*/\n"
        "    \n"
        "    /*background-color: rgb(24, 70, 86);*/\n"
        "    \n"
        "    background-color: rgb(255, 255, 255);\n"
        "    border: none;\n"
        "}\n"
        "QTabBar::tab {\n"
        "    height: 50px;\n"
        "    width: 160px;\n"
        "}\n"
        "QTabBar::tab:selected {\n"
        "    font: 13pt \"icomoon\";\n"
        "    /*background-color: rgb(78, 185, 161);\n"
        "background-color: rgb(140, 133, 255); biru*/\n"
        "    color: rgb(63, 61, 86);\n"
        "    \n"
        "background-color: rgb(255, 255, 255);\n"
        "}\n"
        "QTabBar::tab:!selected {\n"
        "    font: 10pt \"icomoon\";\n"
        "    /*color: rgb(255, 255, 255);\n"
        "    background-color: rgb(24, 70, 86);\n"
        "background-color: rgb(230, 230, 230);*/\n"
        "    \n"
        "    color: white;\n"
        "background-color: rgb(140, 133, 255);\n"
        "}")
                self.tabWDashboard.setTabShape(QtWidgets.QTabWidget.Rounded)
                self.tabWDashboard.setDocumentMode(False)
                self.tabWDashboard.setObjectName("tabWDashboard")
                
                self.tabWDashboard.tabBarClicked.connect(self.reloadProgress)
                
                self.tabBeranda = QtWidgets.QWidget()
                self.tabBeranda.setObjectName("tabBeranda")
                self.label_2 = QtWidgets.QLabel(self.tabBeranda)
                self.label_2.setGeometry(QtCore.QRect(50, 40, 861, 391))
                self.label_2.setStyleSheet("background-color: rgb(230, 230, 230);\n"
        "border-top-left-radius: 15px;\n"
        "border-top-right-radius: 15px;\n"
        "border-bottom-left-radius: 15px;\n"
        "border-bottom-right-radius: 15px;")
                self.label_2.setText("")
                self.label_2.setObjectName("label_2")
                self.label_6 = QtWidgets.QLabel(self.tabBeranda)
                self.label_6.setGeometry(QtCore.QRect(0, 180, 961, 291))
                self.label_6.setStyleSheet("background-color: rgb(47, 46, 65);\n"
        "border-top-left-radius: 15px;\n"
        "border-top-right-radius: 15px;\n"
        "border-bottom-left-radius: 15px;\n"
        "border-bottom-right-radius: 15px;")
                self.label_6.setText("")
                self.label_6.setObjectName("label_6")
                self.label_3 = QtWidgets.QLabel(self.tabBeranda)
                self.label_3.setGeometry(QtCore.QRect(20, 70, 401, 381))
                self.label_3.setText("")
                self.label_3.setPixmap(QtGui.QPixmap(":/images/undraw_new_ideas_jdea.svg"))
                self.label_3.setScaledContents(True)
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(self.tabBeranda)
                self.label_4.setGeometry(QtCore.QRect(420, 130, 461, 61))
                font = QtGui.QFont()
                font.setFamily("Iosevka Custom")
                font.setPointSize(24)
                font.setBold(True)
                font.setUnderline(False)
                font.setWeight(75)
                self.label_4.setFont(font)
                self.label_4.setStyleSheet("color: rgb(63, 61, 86);")
                self.label_4.setObjectName("label_4")
                self.label_7 = QtWidgets.QLabel(self.tabBeranda)
                self.label_7.setGeometry(QtCore.QRect(450, 210, 431, 71))
                font = QtGui.QFont()
                font.setFamily("Segoe UI Semibold")
                font.setPointSize(15)
                font.setBold(False)
                font.setWeight(50)
                self.label_7.setFont(font)
                self.label_7.setStyleSheet("color: rgb(63, 61, 86);")
                self.label_7.setFrameShadow(QtWidgets.QFrame.Plain)
                self.label_7.setObjectName("label_7")
                self.label_8 = QtWidgets.QLabel(self.tabBeranda)
                self.label_8.setGeometry(QtCore.QRect(550, 250, 231, 71))
                font = QtGui.QFont()
                font.setFamily("Segoe UI Semibold")
                font.setPointSize(15)
                font.setBold(False)
                font.setWeight(50)
                self.label_8.setFont(font)
                self.label_8.setStyleSheet("color: rgb(63, 61, 86);")
                self.label_8.setFrameShadow(QtWidgets.QFrame.Plain)
                self.label_8.setObjectName("label_8")
                self.label_9 = QtWidgets.QLabel(self.tabBeranda)
                self.label_9.setGeometry(QtCore.QRect(860, 260, 41, 51))
                font = QtGui.QFont()
                font.setFamily("Fugaz One")
                font.setPointSize(52)
                font.setBold(False)
                font.setWeight(50)
                self.label_9.setFont(font)
                self.label_9.setStyleSheet("color: rgb(63, 61, 86);")
                self.label_9.setFrameShadow(QtWidgets.QFrame.Plain)
                self.label_9.setTextFormat(QtCore.Qt.RichText)
                self.label_9.setObjectName("label_9")
                self.label_10 = QtWidgets.QLabel(self.tabBeranda)
                self.label_10.setGeometry(QtCore.QRect(410, 220, 31, 51))
                font = QtGui.QFont()
                font.setFamily("Fugaz One")
                font.setPointSize(52)
                font.setBold(False)
                font.setWeight(50)
                self.label_10.setFont(font)
                self.label_10.setStyleSheet("color: rgb(63, 61, 86);")
                self.label_10.setFrameShadow(QtWidgets.QFrame.Plain)
                self.label_10.setTextFormat(QtCore.Qt.RichText)
                self.label_10.setObjectName("label_10")
                self.btnHomeBeranda = QtWidgets.QPushButton(self.tabBeranda)
                self.btnHomeBeranda.setGeometry(QtCore.QRect(550, 340, 231, 41))
                font = QtGui.QFont()
                font.setFamily("Iosevka Custom")
                font.setPointSize(11)
                font.setBold(True)
                font.setWeight(75)
                self.btnHomeBeranda.setFont(font)
                self.btnHomeBeranda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.btnHomeBeranda.setStyleSheet("QPushButton {\n"
        "background: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(251, 199, 170, 255), stop:1 rgba(247, 217, 143, 255));\n"
        "border: none;\n"
        "border-radius: 15px;\n"
        "color: rgb(63, 61, 86);\n"
        "padding: 10px;\n"
        "}\n"
        "QPushButton:hover {\n"
        "background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(160, 154, 245, 255), stop:1 rgba(168, 210, 209, 255));\n"
        "}\n"
        "QPushButton:pressed {\n"
        "/*background: qlineargradient(x1:0, y0:0, x2:1, y2:1, stop:0 #b3c1ff, stop:1 #b5e4ff);*/\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(104, 95, 245, 255), stop:1 rgba(170, 189, 189, 255));\n"
        "}")
                self.btnHomeBeranda.setObjectName("btnHomeBeranda")
                
                #============ LINK GO TO PENGAJUAN IDE ===============#
                self.btnHomeBeranda.clicked.connect(self.toTabPengajuan)
                
                self.label_11 = QtWidgets.QLabel(self.tabBeranda)
                self.label_11.setGeometry(QtCore.QRect(560, 350, 231, 41))
                font = QtGui.QFont()
                font.setFamily("Fugaz One")
                font.setPointSize(52)
                font.setBold(False)
                font.setWeight(50)
                self.label_11.setFont(font)
                self.label_11.setStyleSheet("background-color: rgba(0, 0, 0, 40);\n"
        "border-radius: 15px;")
                self.label_11.setFrameShadow(QtWidgets.QFrame.Plain)
                self.label_11.setText("")
                self.label_11.setTextFormat(QtCore.Qt.RichText)
                self.label_11.setObjectName("label_11")
                self.label_6.raise_()
                self.label_2.raise_()
                self.label_3.raise_()
                self.label_4.raise_()
                self.label_7.raise_()
                self.label_8.raise_()
                self.label_9.raise_()
                self.label_10.raise_()
                self.label_11.raise_()
                self.btnHomeBeranda.raise_()
                self.tabWDashboard.addTab(self.tabBeranda, "")
                self.tabProfile = QtWidgets.QWidget()
                self.tabProfile.setObjectName("tabProfile")
                self.label = QtWidgets.QLabel(self.tabProfile)
                self.label.setGeometry(QtCore.QRect(30, 60, 331, 161))
                self.label.setStyleSheet("")
                self.label.setText("")
                self.label.setPixmap(QtGui.QPixmap(":/images/undraw_personal_info_0okl.svg"))
                self.label.setScaledContents(True)
                self.label.setObjectName("label")
                self.label_59 = QtWidgets.QLabel(self.tabProfile)
                self.label_59.setGeometry(QtCore.QRect(430, 40, 151, 17))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_59.setFont(font)
                self.label_59.setStyleSheet("color: rgb(140, 133, 255);")
                self.label_59.setObjectName("label_59")
                self.lineEdit = QtWidgets.QLineEdit(self.tabProfile)
                self.lineEdit.setGeometry(QtCore.QRect(430, 60, 231, 41))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.lineEdit.setFont(font)
                self.lineEdit.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
        "border: none;\n"
        "border-bottom:2px solid rgb(92, 98, 110);\n"
        "border-top:5px solid rgb(92, 98, 110);\n"
        "border-right:5px solid rgb(92, 98, 110);\n"
        "border-left:2px solid rgb(92, 98, 110);\n"
        "border-top-right-radius: 40px;\n"
        "\n"
        "/*color: rgb(204, 204, 204);*/\n"
        "color: rgb(63, 61, 86);")
                self.lineEdit.setObjectName("lineEdit")
                self.lineEdit_2 = QtWidgets.QLineEdit(self.tabProfile)
                self.lineEdit_2.setGeometry(QtCore.QRect(430, 140, 231, 41))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.lineEdit_2.setFont(font)
                self.lineEdit_2.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
        "border: none;\n"
        "border-bottom:2px solid rgb(92, 98, 110);\n"
        "border-top:5px solid rgb(92, 98, 110);\n"
        "border-right:5px solid rgb(92, 98, 110);\n"
        "border-left:2px solid rgb(92, 98, 110);\n"
        "border-top-right-radius: 40px;\n"
        "\n"
        "/*color: rgb(204, 204, 204);*/\n"
        "color: rgb(63, 61, 86);")
                self.lineEdit_2.setObjectName("lineEdit_2")
                self.label_60 = QtWidgets.QLabel(self.tabProfile)
                self.label_60.setGeometry(QtCore.QRect(430, 120, 151, 17))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_60.setFont(font)
                self.label_60.setStyleSheet("color: rgb(140, 133, 255);")
                self.label_60.setObjectName("label_60")
                self.label_61 = QtWidgets.QLabel(self.tabProfile)
                self.label_61.setGeometry(QtCore.QRect(430, 200, 151, 17))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_61.setFont(font)
                self.label_61.setStyleSheet("color: rgb(140, 133, 255);")
                self.label_61.setObjectName("label_61")
                self.pAlamat_3 = QtWidgets.QTextEdit(self.tabProfile)
                self.pAlamat_3.setGeometry(QtCore.QRect(430, 220, 231, 103))
                font = QtGui.QFont()
                font.setFamily("icomoon")
                font.setBold(True)
                font.setWeight(75)
                self.pAlamat_3.setFont(font)
                self.pAlamat_3.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
        "border: none;\n"
        "border-bottom:2px solid rgb(92, 98, 110);\n"
        "border-top:5px solid rgb(92, 98, 110);\n"
        "border-right:5px solid rgb(92, 98, 110);\n"
        "border-left:2px solid rgb(92, 98, 110);\n"
        "border-top-right-radius: 40px;\n"
        "\n"
        "/*color: rgb(204, 204, 204);*/\n"
        "color: rgb(63, 61, 86);")
                self.pAlamat_3.setObjectName("pAlamat_3")
                self.label_62 = QtWidgets.QLabel(self.tabProfile)
                self.label_62.setGeometry(QtCore.QRect(430, 340, 151, 17))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_62.setFont(font)
                self.label_62.setStyleSheet("color: rgb(140, 133, 255);")
                self.label_62.setObjectName("label_62")
                self.lineEdit_3 = QtWidgets.QLineEdit(self.tabProfile)
                self.lineEdit_3.setGeometry(QtCore.QRect(430, 360, 231, 41))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.lineEdit_3.setFont(font)
                self.lineEdit_3.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
        "border: none;\n"
        "border-bottom:2px solid rgb(92, 98, 110);\n"
        "border-top:5px solid rgb(92, 98, 110);\n"
        "border-right:5px solid rgb(92, 98, 110);\n"
        "border-left:2px solid rgb(92, 98, 110);\n"
        "border-top-right-radius: 40px;\n"
        "\n"
        "/*color: rgb(204, 204, 204);*/\n"
        "color: rgb(63, 61, 86);")
                self.lineEdit_3.setObjectName("lineEdit_3")
                self.lineEdit_4 = QtWidgets.QLineEdit(self.tabProfile)
                self.lineEdit_4.setGeometry(QtCore.QRect(690, 60, 231, 41))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.lineEdit_4.setFont(font)
                self.lineEdit_4.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
        "border: none;\n"
        "border-bottom:2px solid rgb(92, 98, 110);\n"
        "border-top:5px solid rgb(92, 98, 110);\n"
        "border-right:5px solid rgb(92, 98, 110);\n"
        "border-left:2px solid rgb(92, 98, 110);\n"
        "border-top-right-radius: 40px;\n"
        "\n"
        "/*color: rgb(204, 204, 204);*/\n"
        "color: rgb(63, 61, 86);")
                self.lineEdit_4.setObjectName("lineEdit_4")
                self.label_63 = QtWidgets.QLabel(self.tabProfile)
                self.label_63.setGeometry(QtCore.QRect(690, 40, 151, 17))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_63.setFont(font)
                self.label_63.setStyleSheet("color: rgb(140, 133, 255);")
                self.label_63.setObjectName("label_63")
                self.horizontalLayoutWidget = QtWidgets.QWidget(self.tabProfile)
                self.horizontalLayoutWidget.setGeometry(QtCore.QRect(690, 140, 234, 51))
                self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
                self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
                self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_3.setSpacing(20)
                self.horizontalLayout_3.setObjectName("horizontalLayout_3")
                self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.radioButton_2.setFont(font)
                self.radioButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.radioButton_2.setStyleSheet("QRadioButton {\n"
        "    color:                  rgb(92, 98, 110);\n"
        "}\n"
        "\n"
        "QRadioButton::indicator {\n"
        "    width:                  10px;\n"
        "    height:                 10px;\n"
        "    border-radius:          7px;\n"
        "}\n"
        "\n"
        "QRadioButton::indicator:checked {\n"
        "    background-color:       rgb(140, 133, 255);\n"
        "    border:                 3px solid rgb(189, 187, 187);\n"
        "}\n"
        "\n"
        "QRadioButton::indicator:unchecked {\n"
        "    background-color:       rgb(255, 255, 255);\n"
        "    border:                 2px solid rgb(189, 187, 187);\n"
        "}")
                self.radioButton_2.setObjectName("radioButton_2")
                self.horizontalLayout_3.addWidget(self.radioButton_2)
                self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.radioButton.setFont(font)
                self.radioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.radioButton.setStyleSheet("QRadioButton {\n"
        "    color:                  rgb(92, 98, 110);\n"
        "}\n"
        "\n"
        "QRadioButton::indicator {\n"
        "    width:                  10px;\n"
        "    height:                 10px;\n"
        "    border-radius:          7px;\n"
        "}\n"
        "\n"
        "QRadioButton::indicator:checked {\n"
        "    background-color:      rgb(140, 133, 255);\n"
        "    border:                 3px solid rgb(189, 187, 187);\n"
        "}\n"
        "\n"
        "QRadioButton::indicator:unchecked {\n"
        "    background-color:      rgb(255, 255, 255);\n"
        "    border:                 2px solid rgb(189, 187, 187);\n"
        "}")
                self.radioButton.setObjectName("radioButton")
                self.horizontalLayout_3.addWidget(self.radioButton)
                self.label_69 = QtWidgets.QLabel(self.tabProfile)
                self.label_69.setGeometry(QtCore.QRect(690, 120, 151, 17))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_69.setFont(font)
                self.label_69.setStyleSheet("color: rgb(140, 133, 255);")
                self.label_69.setObjectName("label_69")
                self.label_64 = QtWidgets.QLabel(self.tabProfile)
                self.label_64.setGeometry(QtCore.QRect(690, 200, 151, 17))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_64.setFont(font)
                self.label_64.setStyleSheet("color: rgb(140, 133, 255);")
                self.label_64.setObjectName("label_64")
                self.lineEdit_5 = QtWidgets.QLineEdit(self.tabProfile)
                self.lineEdit_5.setGeometry(QtCore.QRect(690, 220, 231, 41))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.lineEdit_5.setFont(font)
                self.lineEdit_5.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
        "border: none;\n"
        "border-bottom:2px solid rgb(92, 98, 110);\n"
        "border-top:5px solid rgb(92, 98, 110);\n"
        "border-right:5px solid rgb(92, 98, 110);\n"
        "border-left:2px solid rgb(92, 98, 110);\n"
        "border-top-right-radius: 40px;\n"
        "\n"
        "/*color: rgb(204, 204, 204);*/\n"
        "color: rgb(63, 61, 86);")
                self.lineEdit_5.setObjectName("lineEdit_5")
                self.pushButton_3 = QtWidgets.QPushButton(self.tabProfile)
                self.pushButton_3.setGeometry(QtCore.QRect(690, 280, 231, 41))
                font = QtGui.QFont()
                font.setFamily("Iosevka Custom")
                font.setPointSize(11)
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_3.setFont(font)
                self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.pushButton_3.setStyleSheet("QPushButton {\n"
        "background: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(251, 199, 170, 255), stop:1 rgba(247, 217, 143, 255));\n"
        "border: none;\n"
        "border-radius: 10px;\n"
        "color: rgb(63, 61, 86);\n"
        "padding: 10px;\n"
        "}\n"
        "QPushButton:hover {\n"
        "background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(160, 154, 245, 255), stop:1 rgba(168, 210, 209, 255));\n"
        "}\n"
        "QPushButton:pressed {\n"
        "/*background: qlineargradient(x1:0, y0:0, x2:1, y2:1, stop:0 #b3c1ff, stop:1 #b5e4ff);*/\n"
        "    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(104, 95, 245, 255), stop:1 rgba(170, 189, 189, 255));\n"
        "}")
                self.pushButton_3.setObjectName("pushButton_3")
                
                #======= LINK EDIT PROFILE ======#
                self.pushButton_3.clicked.connect(self.editProfile)
                
                self.label_21 = QtWidgets.QLabel(self.tabProfile)
                self.label_21.setGeometry(QtCore.QRect(50, 290, 331, 51))
                font = QtGui.QFont()
                font.setFamily("Segoe UI Black")
                font.setPointSize(18)
                font.setBold(True)
                font.setWeight(75)
                self.label_21.setFont(font)
                self.label_21.setStyleSheet("/*color: rgb(255, 255, 255)*/\n"
        "\n"
        "color: rgb(108, 99, 255);")
                self.label_21.setObjectName("label_21")
                self.label_22 = QtWidgets.QLabel(self.tabProfile)
                self.label_22.setGeometry(QtCore.QRect(50, 320, 81, 51))
                font = QtGui.QFont()
                font.setFamily("Segoe UI Black")
                font.setPointSize(18)
                font.setBold(True)
                font.setWeight(75)
                self.label_22.setFont(font)
                self.label_22.setStyleSheet("color: rgb(108, 99, 255);")
                self.label_22.setObjectName("label_22")
                self.label_15 = QtWidgets.QLabel(self.tabProfile)
                self.label_15.setGeometry(QtCore.QRect(40, 80, 341, 161))
                self.label_15.setStyleSheet("background-color: rgba(9, 0, 0, 55);\n"
        "border-top-left-radius: 161px;")
                self.label_15.setText("")
                self.label_15.setScaledContents(False)
                self.label_15.setObjectName("label_15")
                self.label_15.raise_()
                self.label.raise_()
                self.label_59.raise_()
                self.lineEdit.raise_()
                self.lineEdit_2.raise_()
                self.label_60.raise_()
                self.label_61.raise_()
                self.pAlamat_3.raise_()
                self.label_62.raise_()
                self.lineEdit_3.raise_()
                self.lineEdit_4.raise_()
                self.label_63.raise_()
                self.horizontalLayoutWidget.raise_()
                self.label_69.raise_()
                self.label_64.raise_()
                self.lineEdit_5.raise_()
                self.pushButton_3.raise_()
                self.label_21.raise_()
                self.label_22.raise_()
                self.tabWDashboard.addTab(self.tabProfile, "")
                self.tabAjukan = QtWidgets.QWidget()
                self.tabAjukan.setObjectName("tabAjukan")
                self.label_17 = QtWidgets.QLabel(self.tabAjukan)
                self.label_17.setGeometry(QtCore.QRect(50, 40, 511, 401))
                self.label_17.setText("")
                self.label_17.setPixmap(QtGui.QPixmap(":/images/undraw_folder_39kl.svg"))
                self.label_17.setScaledContents(True)
                self.label_17.setObjectName("label_17")
                self.label_65 = QtWidgets.QLabel(self.tabAjukan)
                self.label_65.setGeometry(QtCore.QRect(634, 60, 151, 17))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_65.setFont(font)
                self.label_65.setStyleSheet("color: rgb(140, 133, 255);")
                self.label_65.setObjectName("label_65")
                self.label_66 = QtWidgets.QLabel(self.tabAjukan)
                self.label_66.setGeometry(QtCore.QRect(634, 130, 151, 17))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_66.setFont(font)
                self.label_66.setStyleSheet("color: rgb(140, 133, 255);")
                self.label_66.setObjectName("label_66")
                self.label_67 = QtWidgets.QLabel(self.tabAjukan)
                self.label_67.setGeometry(QtCore.QRect(634, 200, 151, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_67.setFont(font)
                self.label_67.setStyleSheet("color: rgb(140, 133, 255);")
                self.label_67.setObjectName("label_67")
                self.label_68 = QtWidgets.QLabel(self.tabAjukan)
                self.label_68.setGeometry(QtCore.QRect(634, 240, 151, 17))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_68.setFont(font)
                self.label_68.setStyleSheet("color: rgb(140, 133, 255);")
                self.label_68.setObjectName("label_68")
                self.label_70 = QtWidgets.QLabel(self.tabAjukan)
                self.label_70.setGeometry(QtCore.QRect(634, 310, 151, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_70.setFont(font)
                self.label_70.setStyleSheet("color: rgb(140, 133, 255);")
                self.label_70.setObjectName("label_70")
                self.leAjukanJudul = QtWidgets.QLineEdit(self.tabAjukan)
                self.leAjukanJudul.setGeometry(QtCore.QRect(634, 80, 231, 41))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.leAjukanJudul.setFont(font)
                self.leAjukanJudul.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
        "border: none;\n"
        "border-bottom:2px solid rgb(92, 98, 110);\n"
        "border-top:5px solid rgb(92, 98, 110);\n"
        "border-right:5px solid rgb(92, 98, 110);\n"
        "border-left:2px solid rgb(92, 98, 110);\n"
        "border-top-right-radius: 40px;\n"
        "\n"
        "/*color: rgb(204, 204, 204);*/\n"
        "color: rgb(63, 61, 86);")
                self.leAjukanJudul.setObjectName("leAjukanJudul")
                self.leAjukanDesc = QtWidgets.QLineEdit(self.tabAjukan)
                self.leAjukanDesc.setGeometry(QtCore.QRect(634, 150, 231, 41))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.leAjukanDesc.setFont(font)
                self.leAjukanDesc.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
        "border: none;\n"
        "border-bottom:2px solid rgb(92, 98, 110);\n"
        "border-top:5px solid rgb(92, 98, 110);\n"
        "border-right:5px solid rgb(92, 98, 110);\n"
        "border-left:2px solid rgb(92, 98, 110);\n"
        "border-top-right-radius: 40px;\n"
        "\n"
        "/*color: rgb(204, 204, 204);*/\n"
        "color: rgb(63, 61, 86);")
                self.leAjukanDesc.setObjectName("leAjukanDesc")
                self.btnAjukanProposal = QtWidgets.QPushButton(self.tabAjukan)
                self.btnAjukanProposal.setGeometry(QtCore.QRect(764, 200, 101, 31))
                font = QtGui.QFont()
                font.setFamily("Segoe UI Semibold")
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.btnAjukanProposal.setFont(font)
                self.btnAjukanProposal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.btnAjukanProposal.setStyleSheet("QPushButton {\n"
        "background-color: rgb(63, 61, 86);\n"
        "border: none;\n"
        "border-radius: 4px;\n"
        "color: rgb(255, 255, 255);\n"
        "padding: 10px;\n"
        "}\n"
        "QPushButton:hover {\n"
        "background: rgb(80, 78, 101);\n"
        "}\n"
        "QPushButton:pressed {\n"
        "/*background: qlineargradient(x1:0, y0:0, x2:1, y2:1, stop:0 #b3c1ff, stop:1 #b5e4ff);*/\n"
        "    background-color: rgb(47, 46, 65);\n"
        "}")
                self.btnAjukanProposal.setObjectName("btnAjukanProposal")
                
                #===== OPEN FILE PROPOSAL =======#
                self.btnAjukanProposal.clicked.connect(self.loadProposal)
                
                self.leAjukanOrganisasi = QtWidgets.QLineEdit(self.tabAjukan)
                self.leAjukanOrganisasi.setGeometry(QtCore.QRect(634, 260, 231, 41))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.leAjukanOrganisasi.setFont(font)
                self.leAjukanOrganisasi.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
        "border: none;\n"
        "border-bottom:2px solid rgb(92, 98, 110);\n"
        "border-top:5px solid rgb(92, 98, 110);\n"
        "border-right:5px solid rgb(92, 98, 110);\n"
        "border-left:2px solid rgb(92, 98, 110);\n"
        "border-top-right-radius: 40px;\n"
        "\n"
        "/*color: rgb(204, 204, 204);*/\n"
        "color: rgb(63, 61, 86);")
                self.leAjukanOrganisasi.setObjectName("leAjukanOrganisasi")
                self.spinAnggota = QtWidgets.QSpinBox(self.tabAjukan)
                self.spinAnggota.setGeometry(QtCore.QRect(760, 310, 101, 31))
                self.spinAnggota.setObjectName("spinAnggota")
                
                self.spinAnggota.valueChanged.connect(self.valuechange)
                
                self.btnAjukanSubmit = QtWidgets.QPushButton(self.tabAjukan)
                self.btnAjukanSubmit.setGeometry(QtCore.QRect(630, 350, 241, 41))
                font = QtGui.QFont()
                font.setFamily("Iosevka Custom")
                font.setPointSize(11)
                font.setBold(True)
                font.setWeight(75)
                self.btnAjukanSubmit.setFont(font)
                self.btnAjukanSubmit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.btnAjukanSubmit.setStyleSheet("QPushButton {\n"
        "background: rgb(87, 184, 148);\n"
        "border: none;\n"
        "border-radius: 10px;\n"
        "color: rgb(63, 61, 86);\n"
        "padding: 10px;\n"
        "}\n"
        "QPushButton:hover {\n"
        "background: rgba(87, 184, 148, 171);\n"
        "}\n"
        "QPushButton:pressed {\n"
        "/*background: qlineargradient(x1:0, y0:0, x2:1, y2:1, stop:0 #b3c1ff, stop:1 #b5e4ff);*/\n"
        "    background-color: rgb(74, 156, 126);\n"
        "}")
                self.btnAjukanSubmit.setObjectName("btnAjukanSubmit")
                
                #====== AJUKAN IDE ======#
                self.btnAjukanSubmit.clicked.connect(self.daftarIde)
                
                self.tabWDashboard.addTab(self.tabAjukan, "")
                self.tabProgress = QtWidgets.QWidget()
                self.tabProgress.setStyleSheet("")
                self.tabProgress.setObjectName("tabProgress")
                self.label_58 = QtWidgets.QLabel(self.tabProgress)
                self.label_58.setGeometry(QtCore.QRect(380, 30, 301, 41))
                font = QtGui.QFont()
                font.setFamily("Segoe UI Semibold")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.label_58.setFont(font)
                self.label_58.setStyleSheet("color: rgb(140, 133, 255);")
                self.label_58.setObjectName("label_58")
                self.tblProgIde = QtWidgets.QTableWidget(self.tabProgress)
                self.tblProgIde.setGeometry(QtCore.QRect(140, 90, 721, 291))
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(11)
                self.tblProgIde.setFont(font)
                self.tblProgIde.setStyleSheet("color: rgb(85, 85, 255);\n"
        "background-color: rgb(227, 227, 227);")
                self.tblProgIde.setRowCount(11)
                self.tblProgIde.setColumnCount(7)
                self.tblProgIde.setObjectName("tblProgIde")
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                item.setFont(font)
                self.tblProgIde.setVerticalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(9)
                item.setFont(font)
                self.tblProgIde.setVerticalHeaderItem(1, item)
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(9)
                item.setFont(font)
                self.tblProgIde.setVerticalHeaderItem(2, item)
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(9)
                item.setFont(font)
                self.tblProgIde.setVerticalHeaderItem(3, item)
                item = QtWidgets.QTableWidgetItem()
                self.tblProgIde.setVerticalHeaderItem(4, item)
                item = QtWidgets.QTableWidgetItem()
                self.tblProgIde.setVerticalHeaderItem(5, item)
                item = QtWidgets.QTableWidgetItem()
                self.tblProgIde.setVerticalHeaderItem(6, item)
                item = QtWidgets.QTableWidgetItem()
                self.tblProgIde.setVerticalHeaderItem(7, item)
                item = QtWidgets.QTableWidgetItem()
                self.tblProgIde.setVerticalHeaderItem(8, item)
                item = QtWidgets.QTableWidgetItem()
                self.tblProgIde.setVerticalHeaderItem(9, item)
                item = QtWidgets.QTableWidgetItem()
                self.tblProgIde.setVerticalHeaderItem(10, item)
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                item.setFont(font)
                self.tblProgIde.setHorizontalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                item.setFont(font)
                self.tblProgIde.setHorizontalHeaderItem(1, item)
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                item.setFont(font)
                self.tblProgIde.setHorizontalHeaderItem(2, item)
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setBold(True)
                font.setWeight(75)
                item.setFont(font)
                self.tblProgIde.setHorizontalHeaderItem(3, item)
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                item.setFont(font)
                self.tblProgIde.setHorizontalHeaderItem(4, item)
                item = QtWidgets.QTableWidgetItem()
                self.tblProgIde.setHorizontalHeaderItem(5, item)
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setBold(True)
                font.setWeight(75)
                item.setFont(font)
                self.tblProgIde.setHorizontalHeaderItem(6, item)
                self.label_5 = QtWidgets.QLabel(self.tabProgress)
                self.label_5.setGeometry(QtCore.QRect(-20, 330, 161, 171))
                self.label_5.setText("")
                self.label_5.setPixmap(QtGui.QPixmap(":/images/undraw_No_data_re_kwbl.svg"))
                self.label_5.setScaledContents(True)
                self.label_5.setObjectName("label_5")
                self.label_13 = QtWidgets.QLabel(self.tabProgress)
                self.label_13.setGeometry(QtCore.QRect(130, 76, 741, 341))
                self.label_13.setStyleSheet("background-color: rgba(0, 0, 0, 50);\n"
        "border-top-left-radius: 5px;\n"
        "border-top-right-radius: 5px;\n"
        "border-bottom-left-radius: 15px;\n"
        "border-bottom-right-radius: 15px;")
                self.label_13.setText("")
                self.label_13.setObjectName("label_13")
                self.label_16 = QtWidgets.QLabel(self.tabProgress)
                self.label_16.setGeometry(QtCore.QRect(840, -10, 161, 171))
                self.label_16.setText("")
                self.label_16.setPixmap(QtGui.QPixmap(":/images/undraw_No_data_re_kwbl.svg"))
                self.label_16.setScaledContents(True)
                self.label_16.setObjectName("label_16")
                self.label_16.raise_()
                self.label_5.raise_()
                self.label_58.raise_()
                self.label_13.raise_()
                self.tblProgIde.raise_()
                self.tabWDashboard.addTab(self.tabProgress, "")
                self.tabLihatIde = QtWidgets.QWidget()
                self.tabLihatIde.setObjectName("tabLihatIde")
                self.label_20 = QtWidgets.QLabel(self.tabLihatIde)
                self.label_20.setGeometry(QtCore.QRect(840, -10, 161, 171))
                self.label_20.setText("")
                self.label_20.setPixmap(QtGui.QPixmap(":/images/undraw_No_data_re_kwbl.svg"))
                self.label_20.setScaledContents(True)
                self.label_20.setObjectName("label_20")
                self.label_27 = QtWidgets.QLabel(self.tabLihatIde)
                self.label_27.setGeometry(QtCore.QRect(180, 76, 631, 341))
                self.label_27.setStyleSheet("background-color: rgba(0, 0, 0, 50);\n"
        "border-top-left-radius: 5px;\n"
        "border-top-right-radius: 5px;\n"
        "border-bottom-left-radius: 15px;\n"
        "border-bottom-right-radius: 15px;")
                self.label_27.setText("")
                self.label_27.setObjectName("label_27")
                self.label_34 = QtWidgets.QLabel(self.tabLihatIde)
                self.label_34.setGeometry(QtCore.QRect(-20, 330, 161, 171))
                self.label_34.setText("")
                self.label_34.setPixmap(QtGui.QPixmap(":/images/undraw_No_data_re_kwbl.svg"))
                self.label_34.setScaledContents(True)
                self.label_34.setObjectName("label_34")
                self.label_71 = QtWidgets.QLabel(self.tabLihatIde)
                self.label_71.setGeometry(QtCore.QRect(350, 30, 301, 41))
                font = QtGui.QFont()
                font.setFamily("Segoe UI Semibold")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.label_71.setFont(font)
                self.label_71.setStyleSheet("color: rgb(140, 133, 255);")
                self.label_71.setAlignment(QtCore.Qt.AlignCenter)
                self.label_71.setObjectName("label_71")
                self.tblListIde = QtWidgets.QTableWidget(self.tabLihatIde)
                self.tblListIde.setGeometry(QtCore.QRect(190, 90, 611, 291))
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(11)
                self.tblListIde.setFont(font)
                self.tblListIde.setStyleSheet("color: rgb(85, 85, 255);\n"
        "background-color: rgb(227, 227, 227);")
                self.tblListIde.setRowCount(11)
                self.tblListIde.setColumnCount(6)
                self.tblListIde.setObjectName("tblListIde")
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                item.setFont(font)
                self.tblListIde.setVerticalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(9)
                item.setFont(font)
                self.tblListIde.setVerticalHeaderItem(1, item)
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(9)
                item.setFont(font)
                self.tblListIde.setVerticalHeaderItem(2, item)
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(9)
                item.setFont(font)
                self.tblListIde.setVerticalHeaderItem(3, item)
                item = QtWidgets.QTableWidgetItem()
                self.tblListIde.setVerticalHeaderItem(4, item)
                item = QtWidgets.QTableWidgetItem()
                self.tblListIde.setVerticalHeaderItem(5, item)
                item = QtWidgets.QTableWidgetItem()
                self.tblListIde.setVerticalHeaderItem(6, item)
                item = QtWidgets.QTableWidgetItem()
                self.tblListIde.setVerticalHeaderItem(7, item)
                item = QtWidgets.QTableWidgetItem()
                self.tblListIde.setVerticalHeaderItem(8, item)
                item = QtWidgets.QTableWidgetItem()
                self.tblListIde.setVerticalHeaderItem(9, item)
                item = QtWidgets.QTableWidgetItem()
                self.tblListIde.setVerticalHeaderItem(10, item)
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                item.setFont(font)
                self.tblListIde.setHorizontalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                item.setFont(font)
                self.tblListIde.setHorizontalHeaderItem(1, item)
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                item.setFont(font)
                self.tblListIde.setHorizontalHeaderItem(2, item)
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setBold(True)
                font.setWeight(75)
                item.setFont(font)
                self.tblListIde.setHorizontalHeaderItem(3, item)
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                item.setFont(font)
                self.tblListIde.setHorizontalHeaderItem(4, item)
                item = QtWidgets.QTableWidgetItem()
                self.tblListIde.setHorizontalHeaderItem(5, item)
                self.tabWDashboard.addTab(self.tabLihatIde, "")
                self.tabWinner = QtWidgets.QWidget()
                self.tabWinner.setObjectName("tabWinner")
                self.label_18 = QtWidgets.QLabel(self.tabWinner)
                self.label_18.setGeometry(QtCore.QRect(290, 30, 391, 231))
                self.label_18.setText("")
                self.label_18.setPixmap(QtGui.QPixmap(":/images/undraw_winners_ao2o.svg"))
                self.label_18.setScaledContents(True)
                self.label_18.setObjectName("label_18")
                self.label_19 = QtWidgets.QLabel(self.tabWinner)
                self.label_19.setGeometry(QtCore.QRect(240, 250, 491, 161))
                self.label_19.setStyleSheet("background-color: rgb(140, 133, 255);\n"
        "border-radius: 30px;")
                self.label_19.setText("")
                self.label_19.setScaledContents(False)
                self.label_19.setObjectName("label_19")
                self.label_14 = QtWidgets.QLabel(self.tabWinner)
                self.label_14.setGeometry(QtCore.QRect(340, 260, 271, 61))
                font = QtGui.QFont()
                font.setFamily("Iosevka Custom")
                font.setPointSize(24)
                font.setBold(True)
                font.setUnderline(False)
                font.setWeight(75)
                self.label_14.setFont(font)
                self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
                self.label_14.setObjectName("label_14")
                self.lblWinner = QtWidgets.QLabel(self.tabWinner)
                self.lblWinner.setGeometry(QtCore.QRect(360, 330, 241, 61))
                font = QtGui.QFont()
                font.setFamily("Iosevka Custom")
                font.setPointSize(24)
                font.setBold(True)
                font.setUnderline(False)
                font.setWeight(75)
                self.lblWinner.setFont(font)
                self.lblWinner.setStyleSheet("color: rgb(63, 61, 85)")
                self.lblWinner.setObjectName("lblWinner")
                self.label_23 = QtWidgets.QLabel(self.tabWinner)
                self.label_23.setGeometry(QtCore.QRect(240, 270, 491, 161))
                self.label_23.setStyleSheet("background-color: rgba(0, 0, 0, 50);\n"
        "border-radius: 30px;")
                self.label_23.setText("")
                self.label_23.setScaledContents(False)
                self.label_23.setObjectName("label_23")
                self.label_23.raise_()
                self.label_19.raise_()
                self.label_18.raise_()
                self.label_14.raise_()
                self.lblWinner.raise_()
                self.tabWDashboard.addTab(self.tabWinner, "")
                self.btnLogout = QtWidgets.QPushButton(Dialog)
                self.btnLogout.setGeometry(QtCore.QRect(855, 0, 61, 51))
                font = QtGui.QFont()
                font.setPointSize(24)
                self.btnLogout.setFont(font)
                self.btnLogout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.btnLogout.setStyleSheet("image: url(:/images/undraw_Login_re_4vu2.svg);")
                self.btnLogout.setText("")
                icon = QtGui.QIcon.fromTheme("ddd")
                self.btnLogout.setIcon(icon)
                self.btnLogout.setFlat(True)
                self.btnLogout.setObjectName("btnLogout")
                
                #-----------logout button----------#
                self.btnLogout.clicked.connect(Dialog.close)
                QMetaObject.connectSlotsByName(Dialog)
                
                self.label_12 = QtWidgets.QLabel(Dialog)
                self.label_12.setGeometry(QtCore.QRect(-10, -60, 951, 451))
                self.label_12.setStyleSheet("background-color: rgb(140, 133, 255);")
                self.label_12.setText("")
                self.label_12.setScaledContents(True)
                self.label_12.setObjectName("label_12")
                self.label_24 = QtWidgets.QLabel(Dialog)
                self.label_24.setGeometry(QtCore.QRect(865, 49, 51, 20))
                font = QtGui.QFont()
                font.setFamily("Leelawadee UI")
                font.setBold(True)
                font.setWeight(75)
                self.label_24.setFont(font)
                self.label_24.setStyleSheet("color: rgb(44, 62, 80);")
                self.label_24.setObjectName("label_24")
                self.label_25 = QtWidgets.QLabel(Dialog)
                self.label_25.setGeometry(QtCore.QRect(850, 0, 71, 51))
                font = QtGui.QFont()
                font.setFamily("Leelawadee UI")
                font.setBold(True)
                font.setWeight(75)
                self.label_25.setFont(font)
                self.label_25.setStyleSheet("background-color: rgb(68, 107, 176);")
                self.label_25.setText("")
                self.label_25.setObjectName("label_25")
                self.label_26 = QtWidgets.QLabel(Dialog)
                self.label_26.setGeometry(QtCore.QRect(850, 50, 71, 21))
                font = QtGui.QFont()
                font.setFamily("Leelawadee UI")
                font.setBold(True)
                font.setWeight(75)
                self.label_26.setFont(font)
                self.label_26.setStyleSheet("background-color: rgb(230, 230, 230);\n"
        "border-bottom-left-radius: 15px;\n"
        "border-bottom-right-radius: 15px;")
                self.label_26.setText("")
                self.label_26.setObjectName("label_26")
                self.label_28 = QtWidgets.QLabel(Dialog)
                self.label_28.setGeometry(QtCore.QRect(0, 0, 791, 41))
                font = QtGui.QFont()
                font.setFamily("Leelawadee UI")
                font.setBold(True)
                font.setWeight(75)
                self.label_28.setFont(font)
                self.label_28.setStyleSheet("background-color: rgba(255, 234, 167, 210);\n"
        "border-bottom-right-radius: 41px;")
                self.label_28.setText("")
                self.label_28.setObjectName("label_28")
                self.label_29 = QtWidgets.QLabel(Dialog)
                self.label_29.setGeometry(QtCore.QRect(0, 40, 471, 41))
                font = QtGui.QFont()
                font.setFamily("Leelawadee UI")
                font.setBold(True)
                font.setWeight(75)
                self.label_29.setFont(font)
                self.label_29.setStyleSheet("background-color: rgba(0, 184, 148, 210);\n"
        "border-bottom-right-radius: 41px;")
                self.label_29.setText("")
                self.label_29.setObjectName("label_29")
                self.label_30 = QtWidgets.QLabel(Dialog)
                self.label_30.setGeometry(QtCore.QRect(-10, 81, 161, 54))
                font = QtGui.QFont()
                font.setFamily("Leelawadee UI")
                font.setBold(True)
                font.setWeight(75)
                self.label_30.setFont(font)
                self.label_30.setStyleSheet("background-color: rgba(68, 107, 176, 210);\n"
        "border-bottom-right-radius: 41px;")
                self.label_30.setText("")
                self.label_30.setObjectName("label_30")
                self.label_31 = QtWidgets.QLabel(Dialog)
                self.label_31.setGeometry(QtCore.QRect(0, 80, 151, 16))
                font = QtGui.QFont()
                font.setFamily("Leelawadee UI")
                font.setBold(True)
                font.setWeight(75)
                self.label_31.setFont(font)
                self.label_31.setStyleSheet("background-color: rgba(0, 0, 0, 41);\n"
        "border-bottom-right-radius: 41px;")
                self.label_31.setText("")
                self.label_31.setObjectName("label_31")
                self.label_32 = QtWidgets.QLabel(Dialog)
                self.label_32.setGeometry(QtCore.QRect(0, 40, 471, 16))
                font = QtGui.QFont()
                font.setFamily("Leelawadee UI")
                font.setBold(True)
                font.setWeight(75)
                self.label_32.setFont(font)
                self.label_32.setStyleSheet("background-color: rgba(0, 0, 0, 41);\n"
        "border-bottom-right-radius: 8px;")
                self.label_32.setText("")
                self.label_32.setObjectName("label_32")
                self.label_33 = QtWidgets.QLabel(Dialog)
                self.label_33.setGeometry(QtCore.QRect(0, 0, 791, 16))
                font = QtGui.QFont()
                font.setFamily("Leelawadee UI")
                font.setBold(True)
                font.setWeight(75)
                self.label_33.setFont(font)
                self.label_33.setStyleSheet("background-color: rgba(0, 0, 0, 41);\n"
        "border-bottom-right-radius: 8px;")
                self.label_33.setText("")
                self.label_33.setObjectName("label_33")
                self.label_12.raise_()
                self.tabWDashboard.raise_()
                self.label_25.raise_()
                self.btnLogout.raise_()
                self.label_26.raise_()
                self.label_24.raise_()
                self.label_28.raise_()
                self.label_29.raise_()
                self.label_30.raise_()
                self.label_31.raise_()
                self.label_32.raise_()
                self.label_33.raise_()
                
                self.retranslateUi(Dialog)
                self.tabWDashboard.setCurrentIndex(0)
                QtCore.QMetaObject.connectSlotsByName(Dialog)

        def retranslateUi(self, Dialog):
                _translate = QtCore.QCoreApplication.translate
                Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
                self.label_4.setText(_translate("Dialog", "Youth Creative Innovation"))
                self.label_7.setText(_translate("Dialog", "Implementasikan Ide kamu untuk membangun"))
                self.label_8.setText(_translate("Dialog", "Daerah yang lebih maju !"))
                self.label_9.setText(_translate("Dialog", "\""))
                self.label_10.setText(_translate("Dialog", "\""))
                self.btnHomeBeranda.setText(_translate("Dialog", "Ajukan Ide ▶"))
                self.tabWDashboard.setTabText(self.tabWDashboard.indexOf(self.tabBeranda), _translate("Dialog", "🏠 Beranda"))
                self.label_59.setText(_translate("Dialog", "Nama"))
                self.lineEdit.setPlaceholderText(_translate("Dialog", " Update nama disini..."))
                self.lineEdit_2.setPlaceholderText(_translate("Dialog", " Update e-mail disini..."))
                self.label_60.setText(_translate("Dialog", "E-mail"))
                self.label_61.setText(_translate("Dialog", "Alamat"))
                self.pAlamat_3.setPlaceholderText(_translate("Dialog", " Update alamat disini..."))
                self.label_62.setText(_translate("Dialog", "Password"))
                self.lineEdit_3.setPlaceholderText(_translate("Dialog", " Update password disini..."))
                self.lineEdit_4.setPlaceholderText(_translate("Dialog", " Update no hp disini..."))
                self.label_63.setText(_translate("Dialog", "No Telepon"))
                self.radioButton_2.setText(_translate("Dialog", "Laki-Laki"))
                self.radioButton.setText(_translate("Dialog", "Perempuan"))
                self.label_69.setText(_translate("Dialog", "Gender"))
                self.label_64.setText(_translate("Dialog", "Status"))
                self.lineEdit_5.setPlaceholderText(_translate("Dialog", " Update status disini..."))
                self.pushButton_3.setText(_translate("Dialog", "Simpan Perubahan"))
                self.label_21.setText(_translate("Dialog", "Silahkan Perbarui Data Diri"))
                self.label_22.setText(_translate("Dialog", "Anda"))
                self.tabWDashboard.setTabText(self.tabWDashboard.indexOf(self.tabProfile), _translate("Dialog", "🔧 Profile"))
                self.label_65.setText(_translate("Dialog", "Judul"))
                self.label_66.setText(_translate("Dialog", "Deskripsi"))
                self.label_67.setText(_translate("Dialog", "Upload Proposal:"))
                self.label_68.setText(_translate("Dialog", "Nama Organisasi"))
                self.label_70.setText(_translate("Dialog", "Jumlah Anggota:"))
                self.leAjukanJudul.setPlaceholderText(_translate("Dialog", " Update nama disini..."))
                self.leAjukanDesc.setPlaceholderText(_translate("Dialog", " Update nama disini..."))
                self.btnAjukanProposal.setText(_translate("Dialog", "Unggah"))
                self.leAjukanOrganisasi.setPlaceholderText(_translate("Dialog", " Update nama disini..."))
                self.btnAjukanSubmit.setText(_translate("Dialog", "Submit"))
                self.tabWDashboard.setTabText(self.tabWDashboard.indexOf(self.tabAjukan), _translate("Dialog", "📝 Ajukan Ide"))
                self.label_58.setText(_translate("Dialog", "Lihat pengajuan ide kamu.."))
                item = self.tblProgIde.horizontalHeaderItem(0)
                item.setText(_translate("Dialog", "No"))
                item = self.tblProgIde.horizontalHeaderItem(1)
                item.setText(_translate("Dialog", "Judul"))
                item = self.tblProgIde.horizontalHeaderItem(2)
                item.setText(_translate("Dialog", "Deskripsi"))
                item = self.tblProgIde.horizontalHeaderItem(3)
                item.setText(_translate("Dialog", "Organisasi"))
                item = self.tblProgIde.horizontalHeaderItem(4)
                item.setText(_translate("Dialog", "Jml Anggota"))
                item = self.tblProgIde.horizontalHeaderItem(5)
                item.setText(_translate("Dialog", "Tanggal"))
                item = self.tblProgIde.horizontalHeaderItem(6)
                item.setText(_translate("Dialog", "Status"))
                self.tabWDashboard.setTabText(self.tabWDashboard.indexOf(self.tabProgress), _translate("Dialog", "⏳ Progress Ide"))
                self.label_71.setText(_translate("Dialog", "List IDE"))
                item = self.tblListIde.horizontalHeaderItem(0)
                item.setText(_translate("Dialog", "No"))
                item = self.tblListIde.horizontalHeaderItem(1)
                item.setText(_translate("Dialog", "Judul"))
                item = self.tblListIde.horizontalHeaderItem(2)
                item.setText(_translate("Dialog", "Deskripsi"))
                item = self.tblListIde.horizontalHeaderItem(3)
                item.setText(_translate("Dialog", "Organisasi"))
                item = self.tblListIde.horizontalHeaderItem(4)
                item.setText(_translate("Dialog", "Jml Anggota"))
                item = self.tblListIde.horizontalHeaderItem(5)
                item.setText(_translate("Dialog", "Tanggal"))
                self.tabWDashboard.setTabText(self.tabWDashboard.indexOf(self.tabLihatIde), _translate("Dialog", "📋 Lihat Ide"))
                self.label_14.setText(_translate("Dialog", "!!! Selamat !!!"))
                self.lblWinner.setText(_translate("Dialog", "{{USER.NAME}}"))
                
                self.lihatIde()
                self.pemenang()
                
                
                self.tabWDashboard.setTabText(self.tabWDashboard.indexOf(self.tabWinner), _translate("Dialog", "🏆 Penghargaan"))
                self.label_24.setText(_translate("Dialog", "Logout"))

            #---------------load data profile user loged in----------------#
        # def loadProfile(self, getId):
        #         dapatId = getId
        #         mydb = mc.connect(
        #                         host = "localhost",
        #                         user = "root",
        #                         password = "",
        #                         database = "inovasiKreatif"
        #                         )
                        
        #         mycursor = mydb.cursor()
        #         #nama, email, alamat, password, hp, gender, pekerjaan, pengalaman, keahlian = range(10)
        #         query = "SELECT * FROM akun WHERE id = " + dapatId
        #         mycursor.execute(query)
        
        #         result = mycursor.fetchall()
        #         if result:
        #                 self.form.lineEdit.setText(result[1])
        #                 self.form.lineEdit_2.setText(result[2])
        #                 self.form.lineEdit_3.setText(result[3])
        #                 if result[4] == 'Laki-laki':
        #                         self.form.radioButton_2.setChecked(True)
        #                         self.form.radioButton.setChecked(False)
        #                 else:
        #                         self.form.radioButton_2.setChecked(False)
        #                         self.form.radioButton.setChecked(True)
        #                 self.form.pAlamat_3.setText(result[5])
        #                 self.form.lineEdit_4.setText(result[6])
        #                 self.form.lineEdit_5.setText(result[7])

        def editProfile(self):
                try:
                        dapatId = self.labelId.text()
                        if self.radioButton_2.isChecked():
                                gender = 'Laki-laki'
                        else:
                                gender = 'Perempuan'
                        
                        mydb = mc.connect(
                                 host = "localhost",
                                 user = "root",
                                 password = "",
                                 database = "inovasiKreatif"
                                 )
                         
                        mycursor = mydb.cursor()
                        query = "UPDATE akun SET nama = %s, email = %s, password = %s, gender = %s, alamat = %s, noHp = %s, status = %s WHERE id = " + dapatId
                        value = (self.lineEdit.text(), self.lineEdit_2.text(), self.lineEdit_3.text(), gender, self.pAlamat_3.toPlainText(), self.lineEdit_4.text(), self.lineEdit_5.text())
                        print("Sukses: Update Profile")
                        QMessageBox.information(self, 'Berhasil Update', 'Profile berhasil di Update!')
                        mycursor.execute(query, value)
                        mydb.commit()
                        
                except mc.Error as e:
                        print("ERROR: Query")
                        
        def daftarIde(self):
                try:
                        
                        mydb = mc.connect(
                                host = "localhost",
                                user = "root",
                                password = "",
                                database = "inovasiKreatif"
                        )
                        mycursor = mydb.cursor()
                        
                        dapatId = self.labelId.text()
                        judul = self.leAjukanJudul.text()
                        deskripsi = self.leAjukanDesc.text()
                        nmOrganisasi = self.leAjukanOrganisasi.text()
                        #jmlAnggota = int(self.spinAnggota.value())
                        jmlAnggota = self.lblJmlAnggota.text()
                        tgl = date.today()
                                
                        queryAdd = "INSERT INTO ideInovasi (idAkun, judul, deskripsi, organisasi, jmlAnggota, tglSubmit) VALUES (%s, %s, %s, %s, %s, %s)"
                        value = (dapatId, judul, deskripsi, nmOrganisasi, jmlAnggota, tgl)
                        
                        if not judul:
                                print("Error: Judul Kosong")
                        else:
                                print("Sukses: Mengajukan Ide")
                                QMessageBox.information(self, 'Pengajuan Berhasil', 'Berhasil mengajukan Ide, Silahkan lihat menu ke progress Ide!')
                                mycursor.execute(queryAdd, value)
                                mydb.commit()
                                self.progressIde(dapatId)
                                self.tabWDashboard.setCurrentIndex(3)
                        
                except mc.Error as e:
                        print("ERROR: Query")         

        def lihatIde(self):
                try:
                        dapatId = self.labelId.text()
                        mydb = mc.connect(
                                host = "localhost",
                                user = "root",
                                password = "",
                                database = "inovasiKreatif"
                                )
                        
                        mycursor = mydb.cursor()
                        query = "SELECT noIde, judul, deskripsi, organisasi, jmlAnggota, tglSubmit FROM ideInovasi"
                        mycursor.execute(query)
                        result = mycursor.fetchall()
                        self.tblListIde.setRowCount(0)
                        
                        for row_number, row_data in enumerate(result):
                                self.tblListIde.insertRow(row_number)
                                for column_number, data in enumerate(row_data):
                                        self.tblListIde.setItem(row_number, column_number, QTableWidgetItem(str(data)))
                                
                except mc.Error as e:
                        print("MYSQL ERROR")
                        
        def progressIde(self, idAkun):
                try:
                        dapatId = idAkun
                        mydb = mc.connect(
                                host = "localhost",
                                user = "root",
                                password = "",
                                database = "inovasiKreatif"
                                )
                                
                        mycursor = mydb.cursor()
                        query = "SELECT noIde, judul, deskripsi, organisasi, jmlAnggota, tglSubmit, status FROM ideInovasi WHERE idAkun = " + dapatId
                        mycursor.execute(query)
                        result = mycursor.fetchall()
                        self.tblProgIde.setRowCount(0)

                        for row_number, row_data in enumerate(result):
                                self.tblProgIde.insertRow(row_number)
                                for column_number, data in enumerate(row_data):
                                        self.tblProgIde.setItem(row_number, column_number, QTableWidgetItem(str(data)))
                                
                except mc.Error as e:
                        print("MYSQL ERROR")
                  
        def pemenang(self):
                mydb = mc.connect(
                        host = "localhost",
                        user = "root",
                        password = "",
                        database = "inovasiKreatif"
                        )
                        
                mycursor = mydb.cursor()
                mycursor2 = mydb.cursor()
                query = "SELECT organisasi FROM ideInovasi WHERE status = 'Selamat anda lolos!'"
                mycursor.execute(query)
                result = mycursor.fetchone()
                if result:
                        self.lblWinner.setText(result[0])

        def valuechange(self):
                self.lblJmlAnggota.setText(str(self.spinAnggota.value()))

        def toTabPengajuan(self, Dialog):
                dapatId = self.labelId.text()
                self.tabWDashboard.setCurrentIndex(2)
                self.lihatIde()
                #self.progressIde(dapatId)
                
        def reloadProgress(self, Dialog):
                dapatId = self.labelId.text()
                self.lihatIde()
                self.progressIde(dapatId)

        #---------------buka dialog open file----------------#
        def loadProposal(self, Dialog):
                fname = QFileDialog.getOpenFileName(self, 'Open file', QDir.currentPath(), "Document files (*.jpg, *.pdf, *.docx *.png)")

if __name__ == "__main__":
        import sys
        app = QApplication(sys.argv)
        Dialog = QDialog()
        ui = Ui_Dialog()
        ui.setupUi(Dialog)
        Dialog.show()
        sys.exit(app.exec_())
