# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# author : @rizky nugraha herliyanto


from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtSql import *
from dashboard import *
import mysql.connector as mc
#import sqlite3
import sys
import Source

class HomePage(QWidget):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(889, 501)
                MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
                MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
                self.centralwidget = QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.label_2 = QLabel(self.centralwidget)
                self.label_2.setGeometry(QRect(570, 0, 321, 501))
                self.label_2.setStyleSheet("background-color: rgb(140, 133, 255);\n"
        "border-bottom-right-radius: 28px;\n"
        "/*border-top-right-radius: 28px;*/")
                self.label_2.setText("")
                self.label_2.setObjectName("label_2")
                self.label_11 = QLabel(self.centralwidget)
                self.label_11.setGeometry(QRect(0, 467, 801, 34))
                self.label_11.setStyleSheet("background-color: rgb(140, 133, 255);\n"
        "border-top-left-radius: 32px;")
                self.label_11.setText("")
                self.label_11.setObjectName("label_11")
                self.tabWMain = QTabWidget(self.centralwidget)
                self.tabWMain.setGeometry(QRect(574, -1, 311, 470))
                self.tabWMain.setCursor(QCursor(Qt.ArrowCursor))
                self.tabWMain.setStyleSheet("QTabWidget::pane {\n"
        "    /*background-color: rgb(137, 204, 247);\n"
        "    background-color: rgb(238, 238, 238);*/\n"
        "    \n"
        "    background-color: rgb(140, 133, 255);\n"
        "    border: none;\n"
        "}\n"
        "QTabWidget::tab-bar {\n"
        "    left: 0px;\n"
        "}\n"
        "QTabBar::tab {\n"
        "    height: 50px;\n"
        "    width: 155px;\n"
        "}\n"
        "QTabBar::tab:selected {\n"
        "    font: 13pt \"icomoon\";\n"
        "    color: rgb(63, 61, 86);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "}\n"
        "QTabBar::tab:!selected {\n"
        "    font: 10pt \"icomoon\";\n"
        "    color: rgb(255, 255, 255);\n"
        "    background-color: rgb(140, 133, 255);\n"
        "}")
                self.tabWMain.setObjectName("tabWMain")
                self.tabMasuk = QWidget()
                self.tabMasuk.setCursor(QCursor(Qt.ArrowCursor))
                self.tabMasuk.setObjectName("tabMasuk")
                self.label_58 = QLabel(self.tabMasuk)
                self.label_58.setGeometry(QRect(430, 40, 321, 161))
                self.label_58.setStyleSheet("background-color: rgb(189, 185, 172);\n"
        "border-top-left-radius: 15px;\n"
        "border-top-right-radius: 15px;\n"
        "border-bottom-left-radius: 15px;\n"
        "border-bottom-right-radius: 15px;")
                self.label_58.setText("")
                self.label_58.setObjectName("label_58")
                self.label_60 = QLabel(self.tabMasuk)
                self.label_60.setGeometry(QRect(437, 50, 321, 161))
                self.label_60.setStyleSheet("background-color: rgba(0, 0, 0, 80);\n"
        "border-top-left-radius: 15px;\n"
        "border-top-right-radius: 15px;\n"
        "border-bottom-left-radius: 15px;\n"
        "border-bottom-right-radius: 15px;")
                self.label_60.setText("")
                self.label_60.setObjectName("label_60")
                self.label_63 = QLabel(self.tabMasuk)
                self.label_63.setGeometry(QRect(430, 240, 321, 161))
                self.label_63.setStyleSheet("background-color: rgb(189, 185, 172);\n"
        "border-top-left-radius: 15px;\n"
        "border-top-right-radius: 15px;\n"
        "border-bottom-left-radius: 15px;\n"
        "border-bottom-right-radius: 15px;")
                self.label_63.setText("")
                self.label_63.setObjectName("label_63")
                self.label_64 = QLabel(self.tabMasuk)
                self.label_64.setGeometry(QRect(437, 250, 321, 161))
                self.label_64.setStyleSheet("background-color: rgba(0, 0, 0, 80);\n"
        "border-top-left-radius: 15px;\n"
        "border-top-right-radius: 15px;\n"
        "border-bottom-left-radius: 15px;\n"
        "border-bottom-right-radius: 15px;")
                self.label_64.setText("")
                self.label_64.setObjectName("label_64")
                self.label_57 = QLabel(self.tabMasuk)
                self.label_57.setGeometry(QRect(0, 30, 311, 51))
                font = QFont()
                font.setFamily("Iosevka")
                font.setPointSize(15)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.label_57.setFont(font)
                self.label_57.setStyleSheet("color: rgb(255, 255, 255);")
                self.label_57.setAlignment(Qt.AlignCenter)
                self.label_57.setObjectName("label_57")
                self.label_59 = QLabel(self.tabMasuk)
                self.label_59.setGeometry(QRect(40, 110, 151, 17))
                font = QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_59.setFont(font)
                self.label_59.setStyleSheet("color: rgb(255, 255, 255);")
                self.label_59.setObjectName("label_59")
                self.leLoginEmail = QLineEdit(self.tabMasuk)
                self.leLoginEmail.setGeometry(QRect(40, 130, 231, 41))
                font = QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.leLoginEmail.setFont(font)
                self.leLoginEmail.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
        "border: none;\n"
        "border-bottom:2px solid rgb(255, 255, 255);\n"
        "border-top:5px solid rgb(255, 255, 255);\n"
        "border-right:5px solid rgb(255, 255, 255);\n"
        "border-left:2px solid rgb(255, 255, 255);\n"
        "border-top-right-radius: 40px;\n"
        "\n"
        "/*color: rgb(204, 204, 204);*/\n"
        "color: rgb(63, 61, 86);")
                self.leLoginEmail.setObjectName("leLoginEmail")
                self.leLoginPassword = QLineEdit(self.tabMasuk)
                self.leLoginPassword.setGeometry(QRect(40, 210, 231, 41))
                font = QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.leLoginPassword.setFont(font)
                self.leLoginPassword.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
        "border: none;\n"
        "border-bottom:2px solid rgb(255, 255, 255);\n"
        "border-top:5px solid rgb(255, 255, 255);\n"
        "border-right:5px solid rgb(255, 255, 255);\n"
        "border-left:2px solid rgb(255, 255, 255);\n"
        "border-top-right-radius: 40px;\n"
        "\n"
        "/*color: rgb(204, 204, 204);*/\n"
        "color: rgb(63, 61, 86);")
                self.leLoginPassword.setEchoMode(QLineEdit.Password)
                self.leLoginPassword.setObjectName("leLoginPassword")
                self.label_61 = QLabel(self.tabMasuk)
                self.label_61.setGeometry(QRect(40, 190, 151, 17))
                font = QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_61.setFont(font)
                self.label_61.setStyleSheet("color: rgb(255, 255, 255);")
                self.label_61.setObjectName("label_61")
                self.btnLogin0 = QPushButton(self.tabMasuk)
                self.btnLogin0.setGeometry(QRect(40, 370, 231, 41))
                font = QFont()
                font.setFamily("Iosevka Custom")
                font.setPointSize(11)
                font.setBold(True)
                font.setWeight(75)
                self.btnLogin0.setFont(font)
                self.btnLogin0.setCursor(QCursor(Qt.PointingHandCursor))
                self.btnLogin0.setStyleSheet("QPushButton {\n"
        "background: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(251, 199, 170, 255), stop:1 rgba(247, 217, 143, 255));\n"
        "border: none;\n"
        "border-radius: 15px;\n"
        "color: rgb(23, 39, 122);\n"
        "padding: 10px;\n"
        "}\n"
        "QPushButton:hover {\n"
        "background: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(251, 199, 170, 255), stop:1 rgba(247, 217, 143, 255));\n"
        "}\n"
        "QPushButton:pressed {\n"
        "/*background: qlineargradient(x1:0, y0:0, x2:1, y2:1, stop:0 #b3c1ff, stop:1 #b5e4ff);*/\n"
        "    background-color: rgb(239, 198, 122);\n"
        "}")
                self.btnLogin0.setObjectName("btnLogin0")
                
                #=========== LINK LOGIN ===============#
                self.btnLogin0.clicked.connect(self.login)
                
                self.label_62 = QLabel(self.tabMasuk)
                self.label_62.setGeometry(QRect(38, 260, 171, 51))
                font = QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(12)
                font.setBold(True)
                font.setItalic(True)
                font.setWeight(75)
                self.label_62.setFont(font)
                self.label_62.setStyleSheet("color: rgb(255, 255, 255);")
                self.label_62.setAlignment(Qt.AlignCenter)
                self.label_62.setObjectName("label_62")
                self.btnGoDaftar = QPushButton(self.tabMasuk)
                self.btnGoDaftar.setGeometry(QRect(213, 273, 61, 25))
                font = QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(11)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.btnGoDaftar.setFont(font)
                self.btnGoDaftar.setCursor(QCursor(Qt.PointingHandCursor))
                self.btnGoDaftar.setStyleSheet("QPushButton {\n"
        "border: none;\n"
        "border-radius: 15px;\n"
        "    color: rgb(24, 39, 122);\n"
        "}\n"
        "QPushButton:hover {\n"
        "color: rgb(46, 126, 251);\n"
        "}\n"
        "QPushButton:pressed {\n"
        "background: qlineargradient(x1:0, y0:0, x2:1, y2:1, stop:0 #b3c1ff, stop:1 #b5e4ff);\n"
        "}")
                self.btnGoDaftar.setFlat(True)
                self.btnGoDaftar.setObjectName("btnGoDaftar")
                
                #--------- LINK BELUM PUNYA AKUN -------#
                self.btnGoDaftar.clicked.connect(self.toTabDaftar)
                
                self.tabWMain.addTab(self.tabMasuk, "")
                self.tabDaftar = QWidget()
                self.tabDaftar.setCursor(QCursor(Qt.ArrowCursor))
                self.tabDaftar.setObjectName("tabDaftar")
                self.label_65 = QLabel(self.tabDaftar)
                self.label_65.setGeometry(QRect(0, 20, 311, 51))
                font = QFont()
                font.setFamily("Iosevka")
                font.setPointSize(15)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.label_65.setFont(font)
                self.label_65.setStyleSheet("color: rgb(255, 255, 255);")
                self.label_65.setAlignment(Qt.AlignCenter)
                self.label_65.setObjectName("label_65")
                self.leDaftarNama = QLineEdit(self.tabDaftar)
                self.leDaftarNama.setGeometry(QRect(40, 100, 231, 41))
                font = QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.leDaftarNama.setFont(font)
                self.leDaftarNama.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
        "border: none;\n"
        "border-bottom:2px solid rgb(255, 255, 255);\n"
        "border-top:5px solid rgb(255, 255, 255);\n"
        "border-right:5px solid rgb(255, 255, 255);\n"
        "border-left:2px solid rgb(255, 255, 255);\n"
        "border-top-right-radius: 40px;\n"
        "\n"
        "/*color: rgb(204, 204, 204);*/\n"
        "color: rgb(63, 61, 86);")
                self.leDaftarNama.setText("")
                self.leDaftarNama.setObjectName("leDaftarNama")
                self.label_66 = QLabel(self.tabDaftar)
                self.label_66.setGeometry(QRect(40, 80, 151, 17))
                font = QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_66.setFont(font)
                self.label_66.setStyleSheet("color: rgb(255, 255, 255);")
                self.label_66.setObjectName("label_66")
                self.label_67 = QLabel(self.tabDaftar)
                self.label_67.setGeometry(QRect(40, 160, 151, 17))
                font = QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_67.setFont(font)
                self.label_67.setStyleSheet("color: rgb(255, 255, 255);")
                self.label_67.setObjectName("label_67")
                self.leDaftarEmail = QLineEdit(self.tabDaftar)
                self.leDaftarEmail.setGeometry(QRect(40, 180, 231, 41))
                font = QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.leDaftarEmail.setFont(font)
                self.leDaftarEmail.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
        "border: none;\n"
        "border-bottom:2px solid rgb(255, 255, 255);\n"
        "border-top:5px solid rgb(255, 255, 255);\n"
        "border-right:5px solid rgb(255, 255, 255);\n"
        "border-left:2px solid rgb(255, 255, 255);\n"
        "border-top-right-radius: 40px;\n"
        "\n"
        "/*color: rgb(204, 204, 204);*/\n"
        "color: rgb(63, 61, 86);")
                self.leDaftarEmail.setText("")
                self.leDaftarEmail.setObjectName("leDaftarEmail")
                self.label_68 = QLabel(self.tabDaftar)
                self.label_68.setGeometry(QRect(40, 240, 151, 17))
                font = QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_68.setFont(font)
                self.label_68.setStyleSheet("color: rgb(255, 255, 255);")
                self.label_68.setObjectName("label_68")
                self.leDaftarPassword = QLineEdit(self.tabDaftar)
                self.leDaftarPassword.setGeometry(QRect(40, 260, 231, 41))
                font = QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.leDaftarPassword.setFont(font)
                self.leDaftarPassword.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
        "border: none;\n"
        "border-bottom:2px solid rgb(255, 255, 255);\n"
        "border-top:5px solid rgb(255, 255, 255);\n"
        "border-right:5px solid rgb(255, 255, 255);\n"
        "border-left:2px solid rgb(255, 255, 255);\n"
        "border-top-right-radius: 40px;\n"
        "\n"
        "/*color: rgb(204, 204, 204);*/\n"
        "color: rgb(63, 61, 86);")
                self.leDaftarPassword.setEchoMode(QLineEdit.Password)
                self.leDaftarPassword.setObjectName("leDaftarPassword")
                self.label_69 = QLabel(self.tabDaftar)
                self.label_69.setGeometry(QRect(40, 320, 151, 17))
                font = QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_69.setFont(font)
                self.label_69.setStyleSheet("color: rgb(255, 255, 255);")
                self.label_69.setObjectName("label_69")
                self.horizontalLayoutWidget = QWidget(self.tabDaftar)
                self.horizontalLayoutWidget.setGeometry(QRect(40, 330, 234, 41))
                self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
                self.horizontalLayout_3 = QHBoxLayout(self.horizontalLayoutWidget)
                self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_3.setSpacing(20)
                self.horizontalLayout_3.setObjectName("horizontalLayout_3")
                self.rbL = QRadioButton(self.horizontalLayoutWidget)
                font = QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.rbL.setFont(font)
                self.rbL.setCursor(QCursor(Qt.PointingHandCursor))
                self.rbL.setStyleSheet("QRadioButton {\n"
        "    color:                  white;\n"
        "}\n"
        "\n"
        "QRadioButton::indicator {\n"
        "    width:                  10px;\n"
        "    height:                 10px;\n"
        "    border-radius:          7px;\n"
        "}\n"
        "\n"
        "QRadioButton::indicator:checked {\n"
        "    background-color:       rgb(68, 107, 176);\n"
        "    border:                 3px solid white;\n"
        "}\n"
        "\n"
        "QRadioButton::indicator:unchecked {\n"
        "    background-color:       rgb(206, 206, 206);\n"
        "    border:                 2px solid white;\n"
        "}")
                self.rbL.setObjectName("rbL")
                self.horizontalLayout_3.addWidget(self.rbL)
                self.rbP = QRadioButton(self.horizontalLayoutWidget)
                font = QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.rbP.setFont(font)
                self.rbP.setCursor(QCursor(Qt.PointingHandCursor))
                self.rbP.setStyleSheet("QRadioButton {\n"
        "    color:                  white;\n"
        "}\n"
        "\n"
        "QRadioButton::indicator {\n"
        "    width:                  10px;\n"
        "    height:                 10px;\n"
        "    border-radius:          7px;\n"
        "}\n"
        "\n"
        "QRadioButton::indicator:checked {\n"
        "    background-color:       rgb(68, 107, 176);\n"
        "    border:                 3px solid white;\n"
        "}\n"
        "\n"
        "QRadioButton::indicator:unchecked {\n"
        "    background-color:       rgb(206, 206, 206);\n"
        "    border:                 2px solid white;\n"
        "}")
                self.rbP.setObjectName("rbP")
                self.horizontalLayout_3.addWidget(self.rbP)
                self.btnDaftar0 = QPushButton(self.tabDaftar)
                self.btnDaftar0.setGeometry(QRect(40, 375, 231, 41))
                font = QFont()
                font.setFamily("Iosevka Custom")
                font.setPointSize(11)
                font.setBold(True)
                font.setWeight(75)
                self.btnDaftar0.setFont(font)
                self.btnDaftar0.setCursor(QCursor(Qt.PointingHandCursor))
                self.btnDaftar0.setStyleSheet("QPushButton {\n"
        "background: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(251, 199, 170, 255), stop:1 rgba(247, 217, 143, 255));\n"
        "border: none;\n"
        "border-radius: 15px;\n"
        "color: rgb(23, 38, 121);\n"
        "padding: 10px;\n"
        "}\n"
        "QPushButton:hover {\n"
        "background: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(251, 199, 170, 255), stop:1 rgba(247, 217, 143, 255));\n"
        "}\n"
        "QPushButton:pressed {\n"
        "/*background: qlineargradient(x1:0, y0:0, x2:1, y2:1, stop:0 #b3c1ff, stop:1 #b5e4ff);*/\n"
        "    background-color: rgb(239, 198, 122);\n"
        "}")
                self.btnDaftar0.setObjectName("btnDaftar0")
                
                #------------ LINK DAFTAR AKUN -------------#
                self.btnDaftar0.clicked.connect(self.register)
                
                self.tabWMain.addTab(self.tabDaftar, "")
                self.label_70 = QLabel(self.centralwidget)
                self.label_70.setGeometry(QRect(0, 40, 571, 411))
                font = QFont()
                font.setFamily("Leelawadee UI")
                font.setBold(True)
                font.setWeight(75)
                self.label_70.setFont(font)
                self.label_70.setStyleSheet("")
                self.label_70.setText("")
                self.label_70.setPixmap(QPixmap(":/images/3081629.jpg"))
                self.label_70.setScaledContents(True)
                self.label_70.setObjectName("label_70")
                self.label_7 = QLabel(self.centralwidget)
                self.label_7.setGeometry(QRect(150, 0, 271, 31))
                font = QFont()
                font.setFamily("Iosevka Custom")
                font.setPointSize(14)
                font.setBold(True)
                font.setItalic(False)
                font.setUnderline(False)
                font.setWeight(75)
                self.label_7.setFont(font)
                self.label_7.setStyleSheet("color: rgb(24, 39, 122);")
                self.label_7.setAlignment(Qt.AlignCenter)
                self.label_7.setObjectName("label_7")
                self.label_71 = QLabel(self.centralwidget)
                self.label_71.setGeometry(QRect(70, 0, 431, 41))
                font = QFont()
                font.setFamily("Leelawadee UI")
                font.setBold(True)
                font.setWeight(75)
                self.label_71.setFont(font)
                self.label_71.setStyleSheet("background-color: rgb(233, 241, 254);\n"
        "border-bottom-left-radius: 41px;\n"
        "border-bottom-right-radius: 41px;")
                self.label_71.setText("")
                self.label_71.setObjectName("label_71")
                self.label_73 = QLabel(self.centralwidget)
                self.label_73.setGeometry(QRect(560, 0, 16, 501))
                self.label_73.setStyleSheet("background-color: rgba(0, 0, 0, 50);\n"
        "border-bottom-right-radius: 28px;\n"
        "/*border-top-right-radius: 28px;*/")
                self.label_73.setText("")
                self.label_73.setObjectName("label_73")
                self.label_72 = QLabel(self.centralwidget)
                self.label_72.setGeometry(QRect(0, 0, 581, 501))
                self.label_72.setStyleSheet("background-color: rgb(255, 255, 255);\n"
        "border-bottom-right-radius: 28px;\n"
        "/*border-top-right-radius: 28px;*/")
                self.label_72.setText("")
                self.label_72.setObjectName("label_72")
                self.label_72.raise_()
                self.label_70.raise_()
                self.label_73.raise_()
                self.label_11.raise_()
                self.label_2.raise_()
                self.tabWMain.raise_()
                self.label_71.raise_()
                self.label_7.raise_()
                MainWindow.setCentralWidget(self.centralwidget)
                self.retranslateUi(MainWindow)
                self.tabWMain.setCurrentIndex(0)
                QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label_57.setText(_translate("MainWindow", "Selamat Datang!"))
                self.label_59.setText(_translate("MainWindow", "E-mail"))
                self.leLoginEmail.setPlaceholderText(_translate("MainWindow", " Masukkan e-mail disini..."))
                self.leLoginPassword.setPlaceholderText(_translate("MainWindow", " Masukkan password disini..."))
                self.label_61.setText(_translate("MainWindow", "Password"))
                self.btnLogin0.setText(_translate("MainWindow", "Masuk!"))
                self.label_62.setText(_translate("MainWindow", "Belum memiliki Akun?"))
                self.btnGoDaftar.setText(_translate("MainWindow", "DAFTAR!"))
                self.tabWMain.setTabText(self.tabWMain.indexOf(self.tabMasuk), _translate("MainWindow", "🏠 Masuk"))
                self.label_65.setText(_translate("MainWindow", "Silahkan Isi Data Anda"))
                self.leDaftarNama.setPlaceholderText(_translate("MainWindow", " Masukkan nama kamu..."))
                self.label_66.setText(_translate("MainWindow", "Nama"))
                self.label_67.setText(_translate("MainWindow", "Email"))
                self.leDaftarEmail.setPlaceholderText(_translate("MainWindow", " Masukkan e-mail kamu..."))
                self.label_68.setText(_translate("MainWindow", "Password"))
                self.leDaftarPassword.setPlaceholderText(_translate("MainWindow", " Masukkan password kamu..."))
                self.label_69.setText(_translate("MainWindow", "Gender"))
                self.rbL.setText(_translate("MainWindow", "Laki-Laki"))
                self.rbP.setText(_translate("MainWindow", "Perempuan"))
                self.btnDaftar0.setText(_translate("MainWindow", "Daftar!"))                
                self.tabWMain.setTabText(self.tabWMain.indexOf(self.tabDaftar), _translate("MainWindow", "👨‍ Daftar"))
                self.label_7.setText(_translate("MainWindow", "Youth Creative Innovation"))

        #================= FUNCTION ===============#
        #---------- REGISTRASI -------------#
        # def addAkun(self):
        #         idAkun = self.getRowCountAkun(MainWindow) + 1
        #         nama = self.leDaftarNama.text()
        #         email = self.leDaftarEmail.text()
        #         password = self.leDaftarPassword.text()
        #         if self.rbL.isChecked():
        #                 gender = 'Laki-laki'
        #         else:
        #                 gender = 'Perempuan'
        #         queryAddAkun = QSqlQuery()
        #         queryAddAkun.exec_("INSERT INTO akun (id, nama, email, password, gender, alamat, hp, status) VALUES (%d, %s, %s, %s, %s, '',  '', '')")
        #         #QMessageBox.information(self, 'Berhasil Registrasi', 'Anda berhasil melakukan registrasi, silahkan ke halaman login untuk masuk!')
        #         self.tabWMain.setCurrentIndex(0)         
        def register(self):
                try:
                        mydb = mc.connect(
                                host = "localhost",
                                user = "root",
                                password = "",
                                database = "inovasiKreatif"
                        )
                        mycursor = mydb.cursor()
                        
                        #idAkun = self.getRowCountAkun(MainWindow) + 1
                        nama = self.leDaftarNama.text()
                        email = self.leDaftarEmail.text()
                        password = self.leDaftarPassword.text()
                        if self.rbL.isChecked():
                                gender = 'Laki-laki'
                        else:
                                gender = 'Perempuan'
                                
                        queryAdd = "INSERT INTO akun (nama, email, password, gender) VALUES (%s, %s, %s, %s)"
                        value = (nama, email, password, gender)
                        
                        if not password:
                                print("Error: Password kosong")
                        else:
                                print("Sukses: Registrasi Berhasil")
                                QMessageBox.information(self, 'Berhasil Registrasi', 'Anda berhasil melakukan registrasi, silahkan ke halaman login untuk masuk')
                                mycursor.execute(queryAdd, value)
                                mydb.commit()
                                self.tabWMain.setCurrentIndex(0)
                        
                except mc.Error as e:
                        print("ERROR: Query") 
        
        #======= LOAD JUMLAH BARIS AKUN ==========#
        # def getRowCountAkun(self, MainWindow):
        #         mydb = mc.connect(
        #                         host = "localhost",
        #                         user = "root",
        #                         password = "",
        #                         database = "inovasiKreatif"
        #                 )
        #         mycursor = mydb.cursor()
        #         query = "SELECT COUNT(*) FROM akun"
        #         mycursor.execute(query)
                
        #         result = mycursor.fetchone(0)
        #         return result

        #=========== Login =========#                       
        def login(self):
                try:
                        email = self.leLoginEmail.text()
                        password = self.leLoginPassword.text()
                        
                        mydb = mc.connect(
                                host = "localhost",
                                user = "root",
                                password = "",
                                database = "inovasiKreatif"
                                )
                        
                        mycursor = mydb.cursor()
                        mycursor2 = mydb.cursor()
                        query = "SELECT id, nama, email, password, gender, alamat, noHp, status FROM akun WHERE email " \
                                "like '"+ email + "' and password like '" \
                                        + password + "'"
                        mycursor.execute(query)
                        result = mycursor.fetchone()
                        
                        if result == None:
                                print("Error: Email atau Password Salah")
                                QMessageBox.warning(self, 'Login Gagal', 'Email dan Password tidak sesuai!')
                        else:
                                print("Sukses: Login berhasil")
                                #=========== AKSES ke Dashboard ===========#
                                MainWindow.close()
                                
                                Dialog = QDialog()
                                self.form = Ui_Dialog()
                                self.form.setupUi(Dialog)
                                if result:
                                        getId = result[0]
                                        #self.form.loadProfile(getId)
                                        self.form.labelId.setText(str(getId))
                                        self.form.lineEdit.setText(result[1])
                                        self.form.lineEdit_2.setText(result[2])
                                        self.form.lineEdit_3.setText(result[3])
                                        if result[4] == 'Laki-laki':
                                                self.form.radioButton_2.setChecked(True)
                                                self.form.radioButton.setChecked(False)
                                        else:
                                                self.form.radioButton_2.setChecked(False)
                                                self.form.radioButton.setChecked(True)
                                        self.form.pAlamat_3.setText(result[5])
                                        self.form.lineEdit_4.setText(result[6])
                                        self.form.lineEdit_5.setText(result[7])
                                Dialog.show()
                                Dialog.exec_()
                                
                except mc.Error as e:
                        print("Error: Query")

        #=========== LINK GO TO DAFTAR ======#
        def toTabDaftar(self, MainWindow):
                self.tabWMain.setCurrentIndex(1)

if __name__ == "__main__":
        import sys
        app1 = QApplication(sys.argv)
        MainWindow = QMainWindow()
        ui = HomePage()
        ui.setupUi(MainWindow)
        MainWindow.show()
        app1.exec_()
